// services.js - Blackbeard Empire Services List (Standard Bank payment only)

module.exports = [
  { name: "CV Creation", keywords: ["cv", "resume", "curriculum vitae"] },
  { name: "Study Buddy", keywords: ["study", "tutor", "school help", "study buddy"] },
  { name: "Proofreading", keywords: ["proofread", "grammar", "editing"] },
  { name: "Website Design", keywords: ["website", "web design", "site"] },
  { name: "App Development", keywords: ["app", "application", "mobile"] },
  { name: "Automation Consulting", keywords: ["automation", "consult", "automate"] },
  { name: "Free Launcher CV", keywords: ["free cv", "starter cv"] },
  { name: "Chatbot Development", keywords: ["chatbot", "bot", "ai bot"] },
  { name: "Cover Letter", keywords: ["cover letter"] },
  { name: "Business Plan", keywords: ["business plan", "startup plan"] },
  { name: "Logo Design", keywords: ["logo"] },
  { name: "Social Media Content", keywords: ["social media content"] },
  { name: "Deck Design", keywords: ["deck", "pitch deck"] },
  { name: "Online Course", keywords: ["course", "online class"] },
  { name: "Technical Writing", keywords: ["technical writing"] },
  { name: "Translation", keywords: ["translate", "translation"] },
  { name: "SEO Optimization", keywords: ["seo", "optimize", "google ranking"] },
  { name: "Content Writing", keywords: ["content writing", "writing", "blog"] },
  { name: "Email Marketing", keywords: ["email marketing"] },
  { name: "Video Editing", keywords: ["video edit", "edit video"] },
  { name: "Voice Over", keywords: ["voice over", "voiceover"] },
  { name: "Digital Marketing", keywords: ["digital marketing", "online marketing"] },
  { name: "Data Analysis", keywords: ["data", "analysis"] },
  { name: "Project Management", keywords: ["project manager", "project management"] },
  { name: "Graphic Design", keywords: ["graphic design", "graphics"] },
  { name: "Social Media Management", keywords: ["social media management"] },
  { name: "Copywriting", keywords: ["copywriting", "sales writing"] },
  { name: "Website Maintenance", keywords: ["site maintenance", "website upkeep"] },
  { name: "IT Support", keywords: ["it support", "technical support"] },
  { name: "Resume Optimization", keywords: ["resume boost", "cv upgrade"] },
  { name: "Online Tutoring", keywords: ["tutor", "online tutoring"] },
  { name: "AI Chatbot Setup", keywords: ["ai setup", "chatbot install"] },
  { name: "Business Naming", keywords: ["naming", "brand naming"] },
  { name: "Sales Funnel", keywords: ["sales funnel", "funnel"] },